name: tasks
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  intl: ^0.19.0
  sqflite: ^2.0.3
  path: ^1.8.0
  lottie: ^3.1.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  permission_handler:
  http:
  connectivity_plus: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 24
  adaptive_icon_background: "assets/logo.png"
  adaptive_icon_foreground: "assets/logo.png"